$\textbf{Content base Recommender System}$

In [22]:
import numpy as np
# Create score matrix for movies 1,2,3 for example 3,5,6
Score= np.array([3, 5, 6])
Score

array([3, 5, 6])

In [23]:
# Create genre matrix for movies 
Genre= np.array([[1,1,0],[1,1,1],[1,0,1]])
Genre

array([[1, 1, 0],
       [1, 1, 1],
       [1, 0, 1]])

In [24]:
taste=Score @ Genre
taste

array([14,  8, 11])

In [25]:
s = taste.sum()

In [27]:
Taste_percent = (taste/s)*100
Taste_percent

array([42.42424242, 24.24242424, 33.33333333])

In [28]:
max(Taste_percent)

42.42424242424242

In [35]:
np.sort(Taste_percent )

array([24.24242424, 33.33333333, 42.42424242])

$\textbf{How to Calculate Cosine Similarity }$

In [37]:
import numpy as np
from numpy.linalg import norm

# define two array
A = np.array([2, 1, 2, 3, 2, 9])
B = np.array([3, 4, 2, 4, 5, 5])

# compute cosine similarity
cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity:", cosine)


Cosine Similarity: 0.8188504723485274


: 