SVD (Singular Value Decompostion)

In [4]:
import numpy as np
from numpy import linalg as LA
# enter rectangular matrix here 
A = np.array([[5, 0, 0], [0, 4, 0]])
A


array([[5, 0, 0],
       [0, 4, 0]])

In [6]:
AT= np.transpose(A)
AT # transpose matrix

array([[5, 0],
       [0, 4],
       [0, 0]])

Singular Left martix $$ S_L= A \cdot A^t $$
This is a symmetric matrix so eignvectors are perpendicular.
In this example two perpendicular vectors in $ R^2 $


In [8]:
S_left = A@ AT # Singular left matrix
S_left

array([[25,  0],
       [ 0, 16]])

Singular Right martix $$ S_R= A^t \cdot A $$
This is a symmetric matrix so eignvectors are perpendicular.
In this example two perpendicular vectors in $ R^3 $


In [9]:
S_right= AT@A
S_right

array([[25,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  0]])

In [16]:
eigvalues_l, eigvectors_l= LA.eig(S_left)
print(f'eignvalues= \n {eigvalues_l}')
print(f'eignvectors= \n {eigvectors_l}')

eignvalues= 
 25.0
eignvectors= 
 [[1. 0.]
 [0. 1.]]


In [14]:
eigvalues_r, eigvectors_r= LA.eig(S_right)
print(f'eignvalues= \n {eigvalues_r}')
print(f'eignvectors= \n {eigvectors_r}')

eignvalues= 
 [25. 16.  0.]
eignvectors= 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


If $ \lambda_1 \geq \lambda_2 $ be eignvalues of $ S_L $ then   $ \lambda_1 \geq \lambda_2 \geq \lambda_3=0 $ are eignvalues of $ S_R $  

In [17]:
lambda1 =eigvalues_l[0]
lambda2 =eigvalues_l[1]

Square root of $\sigma_1= \sqrt\lambda_1 $ and $ \sigma_2= \sqrt\lambda_2 $ are eignvalues of matrix $A$

In [27]:

sigma1 = np.sqrt(lambda1)
sigma2 = np.sqrt(lambda2)
sigma2

4.0

Create $U$ as matrix contains eignvectors of $S_L$

In [23]:
U = eigvectors_l
U

array([[1., 0.],
       [0., 1.]])

Create $V$ as matrix contains eignvectors of $S_R$ and transpose it to be $V^T$

In [24]:
VT= np.transpose(eigvectors_r)
VT

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create $\Sigma$ as diogonal matrix that contais $ \sigma_i $ eigvalues of $A$ on the diagonal.

In [30]:
SIGMA = np.array([[sigma1, 0, 0], [0, sigma2, 0]])
SIGMA

array([[5., 0., 0.],
       [0., 4., 0.]])

Now $A=U \Sigma V^t $

In [31]:
U @ SIGMA @ VT

array([[5., 0., 0.],
       [0., 4., 0.]])